[package]
name = "ethan_ws"
version = "0.1.0"
authors = ["EtomicBomb <ethan@ethan.ws>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.11"
regex = "1.3.6"
lazy_static = "1.4.0"
